CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    password VARCHAR(255),
    phone_number INTEGER,
    address VARCHAR(255),
    profile_picture_url VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS parents (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    password VARCHAR(255),
    phone_number INTEGER,
    address VARCHAR(255),
    profile_picture_url VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS employees (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    phone_number INTEGER,
    address VARCHAR(255),
    profile_picture_url VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS parent_children (
                                               parent_id BIGINT NOT NULL,
                                               child_id  BIGINT NOT NULL,
                                               PRIMARY KEY (parent_id, child_id),
    CONSTRAINT fk_parent_children_parent
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE,
    CONSTRAINT fk_parent_children_child
    FOREIGN KEY (child_id) REFERENCES users(id) ON DELETE CASCADE
    );
