CREATE TABLE employees
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    email               VARCHAR(255),
    password            VARCHAR(255)                            NOT NULL,
    phone_number        INT,
    address             VARCHAR(255),
    profile_picture_url VARCHAR(255),
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE parent_children
(
    child_id  BIGINT NOT NULL,
    parent_id BIGINT NOT NULL,
    CONSTRAINT pk_parent_children PRIMARY KEY (child_id, parent_id)
);

CREATE TABLE parents
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    email               VARCHAR(255),
    password            VARCHAR(255)                            NOT NULL,
    phone_number        INT,
    address             VARCHAR(255),
    profile_picture_url VARCHAR(255),
    CONSTRAINT pk_parents PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    email               VARCHAR(255),
    password            VARCHAR(255)                            NOT NULL,
    phone_number        INT,
    address             VARCHAR(255),
    profile_picture_url VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_name UNIQUE (name);

ALTER TABLE parents
    ADD CONSTRAINT uc_parents_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_name UNIQUE (name);

ALTER TABLE parent_children
    ADD CONSTRAINT fk_parchi_on_parent_profile FOREIGN KEY (parent_id) REFERENCES parents (id);

ALTER TABLE parent_children
    ADD CONSTRAINT fk_parchi_on_user FOREIGN KEY (child_id) REFERENCES users (id);