-- V1: Complete initial schema
-- Includes: employees, parents, children (with birthday), relationships, and WebAuthn support

CREATE TABLE employees (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           name VARCHAR(255) NOT NULL,
                           email VARCHAR(255),
                           password VARCHAR(255) NOT NULL,
                           phone_number INT,
                           address VARCHAR(255),
                           profile_picture_url VARCHAR(255),
                           CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE parents (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         name VARCHAR(255) NOT NULL,
                         email VARCHAR(255),
                         password VARCHAR(255),
                         phone_number INT,
                         address VARCHAR(255),
                         profile_picture_url VARCHAR(255),
                         CONSTRAINT pk_parents PRIMARY KEY (id)
);

CREATE TABLE children (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          email VARCHAR(255),
                          password VARCHAR(255),
                          phone_number INT,
                          address VARCHAR(255),
                          departments VARCHAR(255),
                          birthday DATE,
                          profile_picture_url VARCHAR(255),
                          CONSTRAINT pk_children PRIMARY KEY (id)
);

CREATE TABLE parent_children (
                                 child_id BIGINT NOT NULL,
                                 parent_id BIGINT NOT NULL,
                                 CONSTRAINT pk_parent_children PRIMARY KEY (child_id, parent_id)
);

ALTER TABLE employees ADD CONSTRAINT uc_employees_name UNIQUE (name);
ALTER TABLE parents ADD CONSTRAINT uc_parents_name UNIQUE (name);
ALTER TABLE children ADD CONSTRAINT uc_children_name UNIQUE (name);

ALTER TABLE parent_children
    ADD CONSTRAINT fk_parchi_on_parent_profile
        FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE CASCADE;

ALTER TABLE parent_children
    ADD CONSTRAINT fk_parchi_on_children
        FOREIGN KEY (child_id) REFERENCES children (id) ON DELETE CASCADE;

-- WebAuthn: User credentials table
CREATE TABLE spring_security_webauthn_user_credentials (
                                                           id VARCHAR(255) PRIMARY KEY,
                                                           user_entity_id BYTEA NOT NULL,
                                                           credential_id BYTEA NOT NULL UNIQUE,
                                                           public_key BYTEA NOT NULL,
                                                           sign_count BIGINT NOT NULL,
                                                           transports VARCHAR(255),
                                                           label VARCHAR(255),
                                                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                           last_used_at TIMESTAMP
);

CREATE INDEX idx_webauthn_user_entity_id
    ON spring_security_webauthn_user_credentials(user_entity_id);

CREATE INDEX idx_webauthn_credential_id
    ON spring_security_webauthn_user_credentials(credential_id);

-- WebAuthn: Challenge tokens table
CREATE TABLE spring_security_webauthn_challenges (
                                                     challenge_id VARCHAR(255) PRIMARY KEY,
                                                     challenge_value BYTEA NOT NULL,
                                                     username VARCHAR(255) NOT NULL,
                                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                     expires_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_webauthn_challenge_username
    ON spring_security_webauthn_challenges(username);