CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

ALTER TABLE departments ADD CONSTRAINT uc_departments_name UNIQUE (name);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    phone_number INT,
    address VARCHAR(255),
    profile_picture_url VARCHAR(255),
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE employee_departments (
    employee_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    CONSTRAINT pk_employee_departments PRIMARY KEY (employee_id, department_id)
);

CREATE TABLE parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255),
    phone_number INT,
    address VARCHAR(255),
    profile_picture_url VARCHAR(255),
    CONSTRAINT pk_parents PRIMARY KEY (id)
);

CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255),
    phone_number INT,
    address VARCHAR(255),
    department_id BIGINT,
    birthday DATE,
    profile_picture_url VARCHAR(255),
    additional_notes TEXT,
    CONSTRAINT pk_children PRIMARY KEY (id)
);

CREATE TABLE parent_children (
    parent_id BIGINT NOT NULL,
    child_id BIGINT NOT NULL,
    registration_number INT NOT NULL,
    CONSTRAINT pk_parent_children PRIMARY KEY (parent_id, child_id)
);

ALTER TABLE employees ADD CONSTRAINT uc_employees_name UNIQUE (name);
ALTER TABLE parents ADD CONSTRAINT uc_parents_name UNIQUE (name);
ALTER TABLE children ADD CONSTRAINT uc_children_name UNIQUE (name);

ALTER TABLE employee_departments
    ADD CONSTRAINT fk_empdept_on_employee
        FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE;

ALTER TABLE employee_departments
    ADD CONSTRAINT fk_empdept_on_department
        FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE;

ALTER TABLE children
    ADD CONSTRAINT fk_children_on_department
        FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE parent_children
    ADD CONSTRAINT fk_parchi_on_parent_profile
        FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE CASCADE;

ALTER TABLE parent_children
    ADD CONSTRAINT fk_parchi_on_children
        FOREIGN KEY (child_id) REFERENCES children (id) ON DELETE CASCADE;

-- 1) WebAuthn user entities
-- Used by JdbcPublicKeyCredentialUserEntityRepository
CREATE TABLE IF NOT EXISTS user_entities (
    id            VARCHAR(255) PRIMARY KEY,
    name          VARCHAR(255) NOT NULL UNIQUE,
    display_name  VARCHAR(255) NOT NULL
    );

-- 2) WebAuthn credentials
-- Used by JdbcUserCredentialRepository
CREATE TABLE IF NOT EXISTS user_credentials (
    id                           BIGSERIAL PRIMARY KEY,
    user_entity_user_id          VARCHAR(255) NOT NULL,
    credential_id                VARCHAR(1024) NOT NULL UNIQUE,
    public_key                   TEXT         NOT NULL,
    signature_count              BIGINT       NOT NULL,
    public_key_credential_type   VARCHAR(32)  NOT NULL,
    created                      TIMESTAMP    NOT NULL,
    last_used                    TIMESTAMP,
    label                        VARCHAR(512),
    backup_eligible              BOOLEAN      NOT NULL DEFAULT FALSE,
    backup_state                 BOOLEAN      NOT NULL DEFAULT FALSE,
    uv_initialized               BOOLEAN      NOT NULL DEFAULT FALSE,
    authenticator_transports     VARCHAR(512),
    attestation_object           BYTEA,
    attestation_client_data_json BYTEA,
    CONSTRAINT fk_user_credentials_user_entities
    FOREIGN KEY (user_entity_user_id)
    REFERENCES user_entities(id)
    );

CREATE INDEX IF NOT EXISTS idx_user_credentials_user_id
    ON user_credentials(user_entity_user_id);