CREATE TABLE IF NOT EXISTS child_status_logs (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                 child_id BIGINT NOT NULL,
                                                 status VARCHAR(50) NOT NULL,
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    symptoms TEXT,
    absence_reason TEXT,
    registered_by_employee_id BIGINT NOT NULL,
    CONSTRAINT pk_child_status_logs PRIMARY KEY (id)
    );

-- Use DO blocks for idempotent constraint/index creation
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_child_status_logs_child') THEN
ALTER TABLE child_status_logs
    ADD CONSTRAINT fk_child_status_logs_child
        FOREIGN KEY (child_id) REFERENCES children (id) ON DELETE CASCADE;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_child_status_logs_employee') THEN
ALTER TABLE child_status_logs
    ADD CONSTRAINT fk_child_status_logs_employee
        FOREIGN KEY (registered_by_employee_id) REFERENCES employees (id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_child_status_logs_child_id
    ON child_status_logs(child_id);

CREATE INDEX IF NOT EXISTS idx_child_status_logs_event_time
    ON child_status_logs(child_id, event_time DESC);
